<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPJwIDzo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPJwIDzo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPJwIDzo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPJwIDzo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPJwIDzo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PJwIDzo',
    'container.build_id' => 'e92e115d',
    'container.build_time' => 1560960370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPJwIDzo');
