<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mWoUEXF' shared service.

return $this->privates['.service_locator.mWoUEXF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MainController::savePostToDb' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\MainController:savePostToDb' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
], [
    'App\\Controller\\MainController::savePostToDb' => '?',
    'App\\Controller\\MainController:savePostToDb' => '?',
]);
